name: config-file
version: 0.1.0
ghc-options: -threaded -Wall -fno-warn-name-shadowing

tests:
  unit:
    main: Tests.hs
    source-dirs:
      - test
    dependencies:
      - config-file
      - hspec

library:
  source-dirs:
    - src

dependencies:
 - base
 - bytestring
 - yaml
 - optparse-applicative
 - hspec
