name: profile-demo
version: 0.1.0
ghc-options: -threaded -O2 -fexcess-precision -fasm -Wall -fno-warn-name-shadowing

executables:
  teh-main:
    main: Main.hs
    source-dirs:
      - src

dependencies:
 - base
 - bytestring
