name: booklet-page-calc
version: 0.1.0
ghc-options: -threaded -Wall -fno-warn-name-shadowing

tests:
  unit:
    main: Tests.hs
    source-dirs:
      - test
    dependencies:
      - booklet-page-calc
      - hspec

library:
  source-dirs:
    - src

dependencies:
 - base
 - bytestring
 - hspec
 - optparse-applicative