name: a-la-carte
version: 0.1.0
ghc-options: -threaded -Wall -fno-warn-name-shadowing

executables:
  a-la-carte:
    main: Main.hs
    source-dirs:
      - app
    dependencies:
      - a-la-carte

library:
  source-dirs:
    - src
  other-modules:
    - Paths_a_la_carte

dependencies:
 - base
 - free
 - hashable
 - bytestring
 - contravariant
 - free
 - hashmap
 - MonadRandom
 - text
 - transformers
 - mtl
