[package]
name = "cactusref-app"
version = "0.1.0"
authors = ["Nick"]
edition = "2018"

[[bin]]
name = "cactusref-app"
path = "src/main.rs"

[dependencies.cactusref]
path = "./cactusref"

[dependencies]
log = "0.4.6"
simple_logger = "1.3.0"
