name:                stt-demo
version:             0.1.0.0
github:              "nlinker/playground/haskell/stt-demo"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

library:
  source-dirs: src

executables:
  stt-demo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stt-demo

tests:
  stt-demo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stt-demo

dependencies:
  - base >= 4.7 && < 5
  - hashable
  - STMonadTrans
  - impure-containers
  - primitive
  - qm-interpolated-string
  - lens
  - mtl
  - containers
  - text

